repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=.gitignore]
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
    -   id: go-mod-tidy
    -   id: go-imports
        args: [-w]
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.53.3
    hooks:
    -   id: golangci-lint
